#!/bin/sh
. ./lib_build

# Build the memory module.
make die
make file
make format
make output
make memory

# Build shapes.
make cube
make cube_l

make rectangle
make rectangle_l

make plane
make text_area
